# Patches the secret provider mapping to tell what keyvault to find the secrets from

apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: jore4-backend-secret-mapping
  namespace: hsl-jore4
spec:
  parameters:
    keyvaultName: "hsl-jore4-dev-vault"
