kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  # https://kind.sigs.k8s.io/docs/user/configuration/#pernode-options
  - role: control-plane
    # This can be used to map volumes between pods and the host machine.
    # Can be used to e.g. map secrets and to retrieve test results from robot framework
    # extraMounts:
    #   - hostPath: /path/to/my/files/
    #     containerPath: /files
    kubeadmConfigPatches:
      # This will make sure that the ingress pod runs on this node so that the port mappings will work.
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "ingress-ready=true"
    extraPortMappings:
      # UI
      - containerPort: 80
        hostPort: 3300
        protocol: TCP

      # services that are not accessible through ingress:
      # postgresql
      - containerPort: 30432
        hostPort: 3002
        protocol: TCP
      # mssql
      - containerPort: 30433
        hostPort: 3003
        protocol: TCP
      # jore3 importer
      - containerPort: 30434
        hostPort: 3004
        protocol: TCP
