apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: jore4-hasura-secret-mapping
  namespace: hsl-jore4
spec:
  provider: azure
  parameters:
    useVMManagedIdentity: "true"
    tenantId: "572a41dd-c389-4f0a-b256-aefd1bf149d7"
    keyvaultName: <replace>
    objects: |
      array:
        - |
          objectName: hsl-jore4-public-db-hostname
          objectAlias: db-hostname
          objectType: secret
        - |
          objectName: hsl-jore4-public-db-database
          objectAlias: db-name
          objectType: secret
        - |
          objectName: hsl-jore4-db-admin-username
          objectAlias: db-username
          objectType: secret
        - |
          objectName: hsl-jore4-db-admin-password
          objectAlias: db-password
          objectType: secret
        - |
          objectName: hsl-jore4-hasura-admin-secret
          objectAlias: hasura-admin-secret
          objectType: secret
