# This is a generated file, all modifications will be overwritten!

# Creates some default resource limits for jore4 containers
# Can be overwritten for pods/deployments in case a microservice needs more resources
# See: https://kubernetes.io/docs/tasks/administer-cluster/manage-resources/

apiVersion: v1
kind: LimitRange
metadata:
  namespace: hsl-jore4
  name: mem-limit-range
spec:
  limits:
    - default:
        memory: "1024Mi"
      defaultRequest:
        memory: "512Mi"
      type: Container
---
apiVersion: v1
kind: LimitRange
metadata:
  namespace: hsl-jore4
  name: cpu-limit-range
spec:
  limits:
    - default:
        cpu: "2"
      defaultRequest:
        cpu: "0.1"
      type: Container
