#{{/* add comment that result yaml was generated */}} This is a generated file, all modifications will be overwritten!

# Creates some default resource limits for jore4 containers
# Can be overwritten for pods/deployments in case a microservice needs more resources
# See: https://kubernetes.io/docs/tasks/administer-cluster/manage-resources/

apiVersion: v1
kind: LimitRange
metadata:
  namespace: hsl-jore4
  name: mem-limit-range
spec:
  limits:
    - default:
        memory: "{{ .Values.limitRanges.memory.default }}"
      defaultRequest:
        memory: "{{ .Values.limitRanges.memory.defaultRequest }}"
      type: Container
---
apiVersion: v1
kind: LimitRange
metadata:
  namespace: hsl-jore4
  name: cpu-limit-range
spec:
  limits:
    - default:
        cpu: "{{ .Values.limitRanges.cpu.default }}"
      defaultRequest:
        cpu: "{{ .Values.limitRanges.cpu.defaultRequest }}"
      type: Container
