stage: dev
ingress:
  type: agic
  hostname: dev.jore.hsl.fi
  routes:
    - path: /
      serviceName: ui
      servicePort: 80
    - path: /api/graphql/*
      serviceName: hasura
      servicePort: 8080
    - path: /api/auth/*
      serviceName: auth
      servicePort: 8080
    - path: /api/mbtiles/*
      serviceName: mbtiles
      servicePort: 8000
    - path: /api/mapmatching/*
      serviceName: mapmatching
      servicePort: 8080
microServices:
  hasura:
    env:
      HASURA_GRAPHQL_ENABLE_CONSOLE: "false"
  jore3importer:
    env:
      DIGIROAD_STOP_CSV_FILE_URL: "https://jore4storage.blob.core.windows.net/jore4-digiroad/digiroad_stops_2022_06_08.csv"
      MAP_MATCHING_API_BASEURL: "https://dev.jore.hsl.fi/api/mapmatching"
  auth:
    env:
      SELF_PUBLIC_BASE_URL: "https://dev.jore.hsl.fi"
      LOGINPAGE_URL: "https://dev.jore.hsl.fi"
      LOGOUTPAGE_URL: "https://dev.jore.hsl.fi"
      OIDC_PROVIDER_BASE_URL: "https://hslid-dev.t5.fi"
