apiVersion: v1
kind: ConfigMap
metadata:
  name: "jore4-{{.serviceName}}-local-secrets"
  namespace: hsl-jore4
data:
  {{- range $key, $value := .localSecrets }}
  {{ $key }}: "{{ $value }}"
  {{- end }}
