apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: jore4-{{.serviceName}}-secret-mapping
  namespace: hsl-jore4
spec:
  provider: azure
  parameters:
    useVMManagedIdentity: "true"
    tenantId: "{{ (datasource "Values").tenantId }}"
    keyvaultName: "hsl-jore4-{{ (datasource "Values").stage }}-vault"
    objects: |
      array:
{{- range $key, $value := .secretMappings }}
  {{- if isKind "string" $value }}
        - |
          objectName: {{ $key }}
          objectAlias: {{ $value }}
          objectType: secret
  {{- else }}
{{- /* if value is an array, the secret is mapped to multiple aliases */}}
    {{- range $index, $alias := $value}}
        - |
          objectName: {{ $key }}
          objectAlias: {{ $alias }}
          objectType: secret
    {{- end }}
  {{- end }}
{{- end }}
