apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: jore4-{{.serviceName}}-secret-mapping
  namespace: hsl-jore4
spec:
  provider: azure
  parameters:
    useVMManagedIdentity: "true"
    tenantId: "{{ (datasource "Values").tenantId }}"
    keyvaultName: "hsl-jore4-{{ (datasource "Values").stage }}-vault"
    objects: |
      array:
{{- range $key, $value := .secretMappings }}
        - |
          objectName: {{ $key }}
          objectAlias: {{ $value }}
          objectType: secret
{{- end }}
