apiVersion: v1
kind: Service
metadata:
  name: jore4-{{.serviceName}}
  namespace: hsl-jore4
spec:
  selector:
    app: jore4-{{.serviceName}}
  ports:
{{- range $index, $port := .ports }}
    - protocol: TCP
      port: {{ $port.containerPort }}
      targetPort: {{ $port.containerPort }}
  {{- if (index $port "nodePort") }}
      nodePort: {{ $port.nodePort }}
  {{- end }}
{{- end }}
