---
version: "3.8"
services:
{{- range $name, $srv := .Values.microServices }}
  {{ $name }}:
    container_name: "{{ $srv.serviceName }}"
    image: "{{ $srv.dockerImage }}"
    restart: "unless-stopped"
    networks:
      - jore4
  {{- if (index $srv "env") }}
    environment:
    {{- range $key, $value := $srv.env }}
      {{ $key }}: "{{ $value }}"
    {{- end }}
  {{- end }}
  {{- if (index $srv "ports") }}
    ports:
    {{- range $index, $port := $srv.ports}}
      - "127.0.0.1:{{ $port.localPort }}:{{ $port.containerPort }}"
    {{- end}}
  {{- end }}
  {{- if (index $srv "localSecrets") }}
    secrets:
      {{- range $key, $value := .localSecrets }}
      - {{ $key }}
      {{- end }}
  {{- end }}
{{ end }}
  proxy:
    container_name: proxy
    image: nginx:alpine
    restart: "unless-stopped"
    networks:
      - jore4
    ports:
      - 3301:80
{{/* directly writing default.conf to the container to make the docker-compose file portable */}}
    command: |
      sh -c "sh -s <<EOF
      cat > /etc/nginx/conf.d/default.conf <<'EOT'
{{tmpl.Exec "templates/nginx.conf" . | strings.Indent "        "}}
      EOT
      cat /etc/nginx/conf.d/default.conf
      nginx -g 'daemon off;'
      EOF"

networks:
  jore4:

secrets:
{{- range $name, $srv := .Values.microServices }}
  {{- if (index $srv "localSecrets") }}
  {{- range $key, $value := .localSecrets }}
  {{ $key }}:
    file: ./secrets/{{ $key }}
  {{- /* also creating the secret files on the fly */}}
  {{- file.Write (print "/tmp/clusters/docker-compose/secrets/" $key) $value }}
  {{- end }}
  {{- end }}
{{- end }}
