---
version: "3.8"
services:
{{ range $name, $srv := .Values.microServices }}
  {{ $name }}:
    container_name: "{{ $srv.serviceName }}"
    image: "{{ $srv.dockerImage }}"
    restart: "unless-stopped"
    networks:
      - jore4
  {{- if (index $srv "env") }}
    environment:
    {{- range $key, $value := $srv.env }}
      {{ $key }}: "{{ $value }}"
    {{- end }}
  {{- end }}
  {{- if (index $srv "ports") }}
    ports:
    {{- range $index, $port := $srv.ports}}
      - "127.0.0.1:{{ $port.localPort }}:{{ $port.containerPort }}"
    {{- end}}
  {{- end }}
  {{- if (index $srv "localSecrets") }}
    secrets:
      {{- range $key, $value := .localSecrets }}
      - {{ $key }}
      {{- end }}
  {{- end }}
{{ end }}

  proxy:
    container_name: proxy
    image: nginx:alpine
    restart: "unless-stopped"
    networks:
      - jore4
    ports:
      - 3301:80
    command: |
      bash -c 'bash -s <<EOF
        cat > /etc/nginx/nginx.conf <<EON
{{ tmpl.Exec "templates/nginx.conf" . | strings.Indent "          " }}
      EON
      nginx
      EOF'

networks:
  jore4:

secrets:
{{- range $name, $srv := .Values.microServices }}
  {{- if (index $srv "localSecrets") }}
  {{- range $key, $value := .localSecrets }}
  {{ $key }}:
    file: ./secrets/{{ $key }}
  {{- end }}
  {{- end }}
{{- end }}

# ---
#   ui:
#     container_name: ui
#     image: hsldevcom/jore4-ui:fix-docker-css--72224fc7574d8fb4486b43d8abc6afcf1b7f14c6
#     restart: "unless-stopped"
#     ports:
#       - "127.0.0.1:3302:80"
#     networks:
#       - jore4

#   auth:
#     container_name: auth
#     build: .
#     restart: "unless-stopped"
#     networks:
#       - jore4
#     ports:
#       - "127.0.0.1:3200:8080"
#     environment:
#       API_PATH_PREFIX: "/api"
#       API_PATH_PREFIX_PUBLIC: "/api/auth"
#       SECRET_STORE_BASE_PATH: "/run/secrets"
#       SELF_PUBLIC_BASE_URL: "http://localhost:3301"
#       LOGINPAGE_URL: "http://localhost:3301"
#       LOGOUTPAGE_URL: "http://localhost:3301"
#       OIDC_PROVIDER_BASE_URL: "https://hslid-dev.t5.fi"
#     secrets:
#       - oidc-client-id
#       - oidc-client-secret

#   proxy:
#     container_name: proxy
#     image: nginx:alpine
#     restart: "unless-stopped"
#     depends_on:
#       - auth
#       - ui
#     volumes:
#       - $PWD/nginx-proxy/default.conf:/etc/nginx/conf.d/default.conf:ro
#     networks:
#       - jore4
#     ports:
#       - 3301:80

# networks:
#   jore4:

# secrets:
#   oidc-client-id:
#     file: ./secrets/oidc-client-id
#   oidc-client-secret:
#     file: ./secrets/oidc-client-secret
