# Patches jore4 services to mount secrets as volumes

apiVersion: apps/v1
kind: Deployment
metadata:
  name: jore4-hasura
  namespace: hsl-jore4
spec:
  template:
    spec:
      volumes:
        - name: secrets-store-inline
          configMap:
            name: jore4-hasura-local-secrets
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jore4-auth
  namespace: hsl-jore4
spec:
  template:
    spec:
      volumes:
        - name: secrets-store-inline
          configMap:
            name: jore4-auth-local-secrets
