# Defines test database configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: jore4-test-database-env
  namespace: hsl-jore4
data:
  POSTGRES_DB: jore4e2e
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
