# This is a generated file, all modifications will be overwritten!

# Describes the default environment variables, secrets the deployment template and the service for jore4 hasura instance
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jore4-hasura
  namespace: hsl-jore4
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "jore4-hasura"
  template:
    metadata:
      labels:
        app: "jore4-hasura"
    spec:
      restartPolicy: Always
      containers:
        - name: "jore4-hasura-image"
          image: "hsldevcom/jore4-hasura:fix-metadata--613b29c2d4c6f0ef1cf6f258ab3071b780fa23bd"
          imagePullPolicy: Always
          ports:
          - containerPort: 8080
          envFrom:
            - configMapRef:
                name: "jore4-hasura-env"
          volumeMounts:
            - name: secrets-store-inline
              mountPath: "/mnt/secrets-store"
              readOnly: true
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080

      volumes:
        - name: secrets-store-inline
          configMap:
            name: jore4-hasura-local-secrets

---
apiVersion: v1
kind: Service
metadata:
  name: jore4-hasura
  namespace: hsl-jore4
spec:
  type: ClusterIP
  selector:
    app: jore4-hasura
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: "jore4-hasura-local-secrets"
  namespace: hsl-jore4
data:
  db-hostname: "testdb"
  db-name: "postgres"
  db-password: "postgres"
  db-username: "postgres"
  hasura-admin-secret: "hasura"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: "jore4-hasura-env"
  namespace: hsl-jore4
data:
  HASURA_GRAPHQL_ENABLE_CONSOLE: "false"
  HASURA_GRAPHQL_ENABLE_TELEMETRY: "false"
  HASURA_GRAPHQL_METADATA_DIR: "/hasura-metadata"
  HASURA_GRAPHQL_MIGRATIONS_DIR: "/hasura-migrations"
  HASURA_GRAPHQL_MIGRATIONS_SERVER_TIMEOUT: "60"
  SECRET_STORE_BASE_PATH: "/mnt/secrets-store"


