# This is a generated file, all modifications will be overwritten!

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./jore4-namespace.yaml
  - ./jore4-limit-range.yaml
  - ./jore4-ingress.yaml
  - ./jore4-auth.yaml
  - ./jore4-hasura.yaml
  - ./jore4-jore3importer.yaml
  - ./jore4-mapmatching.yaml
  - ./jore4-mapmatchingdb.yaml
  - ./jore4-mbtiles.yaml
  - ./jore4-mssqltestdb.yaml
  - ./jore4-testdb.yaml
  - ./jore4-ui.yaml
