name: Auto-update deployment manifests

on:
  workflow_dispatch:

  schedule:
    # once a day at 8 AM
    - cron: "0 8 * * *"

  # warning: cannot create pull requests when running this workflow from a push or a pull_request trigger
  # https://github.com/peter-evans/create-pull-request/blob/main/docs/concepts-guidelines.md#restrictions-on-repository-forks
  push:
    branches: ["auto-update"]

jobs:
  auto-update:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        include:
          - service: hasura
            docker-image: jore4-hasura
          - service: ui
            docker-image: jore4-ui
          - service: auth
            docker-image: jore4-auth
          - service: jore3importer
            docker-image: jore4-jore3-importer
          - service: mapmatching
            docker-image: jore4-map-matching
          - service: mbtiles
            docker-image: jore4-mbtiles-server

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Find latest image with "main" tag from docker hub
        run: |
          dockerHubTag="$(curl --silent --get -H \"Accept: application/json\" https://hub.docker.com/v2/repositories/hsldevcom/${{ matrix.docker-image }}/tags/\?page_size=10\&page=1\&name=main\&ordering=last_updated | jq --raw-output 'first(.results[] | select(.name | startswith("main"))).name')"
          echo $dockerHubTag
          dockerHubImage="hsldevcom/${{ matrix.docker-image }}:${dockerHubTag}"
          echo $dockerHubImage
          echo "dockerHubImage=${dockerHubImage}" >> "${GITHUB_ENV}"

      - name: Find current tag from values
        run: |
          localImage="$(yq e '.microServices.${{ matrix.service }}.dockerImage' ./generate/values/common.yaml)"
          echo $localImage
          echo "localImage=${localImage}" >> "${GITHUB_ENV}"

      - name: Update current tag if it differs
        run: |
          echo $dockerHubImage
          echo $localImage
          if [[ "$dockerHubImage" == "$localImage" ]]; then
            echo "The ${{ matrix.service }} version is current, no need to update"
          else
            echo "The ${{ matrix.service }} version is different compared to the docker hub version, updating..."
            yq eval '.microServices.${{ matrix.service }}.dockerImage = strenv(dockerHubImage)' --inplace ./generate/values/common.yaml

            echo "Regenerating gomplate templates"
            ./development.sh generate

            # confirming that we want to create a pull request with the changes
            echo "doPullRequest=true" >> "${GITHUB_ENV}"

            # fixing permissions to allow git operations
            sudo chown -R $USER:$USER .
          fi

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        if: env.doPullRequest == 'true'
        with:
          commit-message: "Auto-update ${{ matrix.service }}"
          branch: "autoupdate/${{ matrix.service }}"
          delete-branch: true
          title: "Auto-update ${{ matrix.service }}"
          body: |
            Auto-generated by [create-pull-request](https://github.com/peter-evans/create-pull-request)
          labels: |
            autoupdate
