name: Auto-update deployment manifests

on:
  # note: only triggering this workflow locally (so not from forks/pull requests, etc.) to avoid
  # exposing the deployment SSH key
  workflow_dispatch:

  schedule:
    # every hour
    - cron: "0 * * * *"

  # warning: cannot create pull requests when running this workflow from a push or a pull_request trigger
  # https://github.com/peter-evans/create-pull-request/blob/main/docs/concepts-guidelines.md#restrictions-on-repository-forks
  push:
    branches: ["auto-update"]

jobs:
  auto-update-main:
    runs-on: ubuntu-20.04

    strategy:
      # slows down the creation of new pull requests to avoid reaching the github api rate limit
      max-parallel: 1
      matrix:
        include:
          # service: the name of the kubernetes/docker-compose service to update
          # docker-image: the name of the docker image in docker hub (e.g. jore4-postgres)
          # tag-prefix: look for the latest version (tag) of the docker image that starts with this prefix
          - service: hasura
            docker-image: jore4-hasura
            tag-prefix: hsl-main
          - service: ui
            docker-image: jore4-ui
            tag-prefix: main
          - service: auth
            docker-image: jore4-auth
            tag-prefix: main
          - service: jore3importer
            docker-image: jore4-jore3-importer
            tag-prefix: main
          - service: mapmatching
            docker-image: jore4-map-matching
            tag-prefix: main
          - service: mbtiles
            docker-image: jore4-mbtiles-server
            tag-prefix: main
          - service: mapmatchingdb
            docker-image: jore4-postgres
            tag-prefix: mapmatching-main

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          # Warning: with this deployment ssh key, we are giving permissions to the workflow to read/write this repository
          # Without this, we can still create pull requests, but CI jobs won't run
          # With this, the CI jobs that are triggered by "push" will be run
          # See: https://github.com/peter-evans/create-pull-request/blob/main/docs/concepts-guidelines.md#triggering-further-workflow-runs
          ssh-key: ${{ secrets.AUTO_UPDATER_SSH_KEY }}

      - name: Find latest image with "main" tag from docker hub
        run: |
          dockerHubTag="$(curl --silent --get -H \"Accept: application/json\" https://hub.docker.com/v2/repositories/hsldevcom/${{ matrix.docker-image }}/tags/\?page_size=100\&page=1\&ordering=last_updated | jq --raw-output 'first(.results[] | select(.name | startswith("${{ matrix.tag-prefix }}"))).name')"
          echo $dockerHubTag
          dockerHubImage="hsldevcom/${{ matrix.docker-image }}:${dockerHubTag}"
          echo $dockerHubImage
          echo "dockerHubImage=${dockerHubImage}" >> "${GITHUB_ENV}"

      - name: Find current tag from values
        run: |
          localImage="$(yq e '.microServices.${{ matrix.service }}.dockerImage' ./generate/values/common.yaml)"
          echo $localImage
          echo "localImage=${localImage}" >> "${GITHUB_ENV}"

      - name: Update current tag if it differs
        run: |
          echo $dockerHubImage
          echo $localImage
          if [[ "$dockerHubImage" == "$localImage" ]]; then
            echo "The ${{ matrix.service }} version is current, no need to update"
          else
            echo "The ${{ matrix.service }} version is different compared to the docker hub version, updating..."
            yq eval '.microServices.${{ matrix.service }}.dockerImage = strenv(dockerHubImage)' --inplace ./generate/values/common.yaml

            echo "Regenerating gomplate templates"
            ./development.sh generate

            # confirming that we want to create a pull request with the changes
            echo "doPullRequest=true" >> "${GITHUB_ENV}"

            # fixing permissions to allow git operations
            sudo chown -R $USER:$USER .
          fi

      - name: Create Pull Request
        # Note: this is the pinned commit hash for version v3.12.1, as of 2.2.2022
        # @tamaspallos: I reviewed this github action's code on 2.2.2022 and have not found anything malicious in it
        uses: peter-evans/create-pull-request@f22a7da129c901513876a2380e2dae9f8e145330
        if: env.doPullRequest == 'true'
        with:
          commit-message: "Auto-update ${{ matrix.service }}"
          branch: "autoupdate/${{ matrix.service }}"
          base: "main"
          delete-branch: true
          title: "Auto-update ${{ matrix.service }}"
          body: |
            This pull request was generated by [JORE4 auto-update workflow](https://github.com/HSLdevcom/jore4-flux/actions/workflows/auto-update.yml)

            ```diff
            - Note: Should rebase it and not create a merge commit.
            ```
          labels: |
            autoupdate
          author: "JORE4 Auto Updater <tamas.pallos@vincit.fi>"

        # To make sure we don't exceed Github API's rate limit, slowing down the process of opening new PRs
      - name: Aaaand wait...
        # if: env.doPullRequest == 'true'
        run: |
          sleep 300

  auto-deploy-e2e-dev:
    # based on https://github.com/peter-evans/create-pull-request/blob/main/docs/examples.md#keep-a-branch-up-to-date-with-another
    runs-on: ubuntu-20.04
    # this job is not actually dependent on 'auto-update-main'.
    # Only listed it here as dependency to enable throttling
    needs: auto-update-main

    strategy:
      # slows down the creation of new pull requests to avoid reaching the github api rate limit
      max-parallel: 1
      matrix:
        include:
          - target: e2e
          - target: dev

    steps:
      - name: Checkout code from main branch
        uses: actions/checkout@v2
        with:
          ref: ${{ matrix.target }}

      - name: Reset branch to main
        run: |
          git fetch origin main:main
          git reset --hard main

      - name: Generate github token for JORE4 auto update app to authenticate
        # Note: this is the pinned commit hash for version v1.5.1, as of 1.4.2022
        # @tamaspallos: I reviewed this github action's code on 1.4.2022 and have not found anything malicious in it
        uses: tibdex/github-app-token@7ce9ffdcdeb2ba82b01b51d6584a6a85872336d4
        id: generate-token
        with:
          app_id: ${{ secrets.AUTO_UPDATER_APP_ID }}
          private_key: ${{ secrets.AUTO_UPDATER_PRIVATE_KEY }}

      # Creating pull requests using an authenticated github application (JORE4 auto update)
      # This will enable triggering CI jobs automatically. More info here:
      # https://github.com/peter-evans/create-pull-request/blob/main/docs/concepts-guidelines.md#authenticating-with-github-app-generated-tokens
      - name: Create Pull Request to target branch
        # Note: this is the pinned commit hash for version v3.12.1, as of 2.2.2022
        # @tamaspallos: I reviewed this github action's code on 2.2.2022 and have not found anything malicious in it
        uses: peter-evans/create-pull-request@f22a7da129c901513876a2380e2dae9f8e145330
        with:
          token: ${{ steps.generate-token.outputs.token }}
          commit-message: "Auto-deploy to ${{ matrix.target }}"
          branch: "autodeploy/${{ matrix.target }}"
          base: "${{ matrix.target }}"
          delete-branch: true
          title: "Auto-deploy to ${{ matrix.target }}"
          # Note: github does not support coloring text, thus using this 'diff' workaround
          # https://stackoverflow.com/questions/11509830/how-to-add-color-to-githubs-readme-md-file
          body: |
            This pull request was generated by [JORE4 auto-update workflow](https://github.com/HSLdevcom/jore4-flux/actions/workflows/auto-update.yml).

            ```diff
            - Note: Should merge this pull request instead of rebasing it.
            ```
          labels: |
            autodeploy
          author: "JORE4 Auto Updater <tamas.pallos@vincit.fi>"

        # To make sure we don't exceed Github API's rate limit, slowing down the process of opening new PRs
      - name: Aaaand wait...
        run: |
          sleep 300
