name: Create e2e github release

on:
  push:
    tags:
      - "e2e-v*"

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Create release
        run: |
          echo tag: ${RELEASE_VERSION}
          echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token
          gh release create ${RELEASE_VERSION} --notes "test release"
          gh release upload ${RELEASE_VERSION} kindcluster.sh kind-cluster.yaml
