name: Doctoc

on:
  push:
    branches:
      # pull request branches created by auto updater
      - "autoupdate/**"
      - "autodeploy/**"
  pull_request:
    branches: ["**"]

jobs:
  verify-doctoc:
    name: Verifies whether table of contents has been updated
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run doctoc on README
        run: ./development.sh toc

      - name: Verify that doctoc command made no changes, so ToC is up to date
        run: '[ -z "$(git status --porcelain)" ]'
