name: Docker-compose release

on:
  push:
    # release only gets updated in case e2e branch changes
    branches: [e2e]

jobs:
  release:
    name: Create release package from docker-compose config and dependencies
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create release
        uses: ./github-actions/create-docker-bundle-release
        with:
          release_name: e2e-docker-compose
