name: Docker-compose release

on:
  push:
    # release only gets updated in case e2e branch changes
    branches: [e2e]

jobs:
  release:
    name: Create release package from docker-compose config and dependencies
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create release
        env:
          RELEASE_VERSION: e2e-docker-compose
        run: |
          echo "Release version: ${RELEASE_VERSION}"
          echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

          # create a version file (to enable tracking version changes)
          echo "${GITHUB_SHA}" > RELEASE_VERSION.txt

          # create a tar.gz of the docker-compose config + dependencies
          tar -czvf e2e-docker-compose.tar.gz RELEASE_VERSION.txt -C clusters/docker-compose .

          # delete and recreate github release
          gh release delete ${RELEASE_VERSION} || echo "There in no previous github release with the name '${RELEASE_VERSION}'"
          gh release create ${RELEASE_VERSION} --notes "docker-compose config with nginx.conf and secrets"

          # append the tar.gz package and also the individual files (just in case) to the release
          gh release upload ${RELEASE_VERSION} clusters/docker-compose/**
          gh release upload ${RELEASE_VERSION} RELEASE_VERSION.txt
          gh release upload ${RELEASE_VERSION} e2e-docker-compose.tar.gz
