name: Docker-compose release

on:
  push:
  pull_request:
    branches: [main]

jobs:
  release:
    name: Create release package from docker-compose config, nginx.conf and secrets
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Left this here in case we need to use git tag for naming the github release
      # - name: Retrieve git tag to be used as github release name
      #   run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Create release
        env:
          RELEASE_VERSION: e2e-docker-compose
        run: |
          echo "Release version: ${RELEASE_VERSION}"
          echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token
          gh release delete ${RELEASE_VERSION} || echo "There in no previous github release with the name '${RELEASE_VERSION}'"
          gh release create ${RELEASE_VERSION} --notes "docker-compose config with nginx.conf and secrets"
          gh release upload ${RELEASE_VERSION} clusters/docker-compose/**
