name: Run e2e tests

on:
  push:
    branches:
      # pull request branches created by auto updater
      - "autoupdate/**"
      - "autodeploy/**"
  pull_request:
    branches: ["**"]

jobs:
  run-e2e-tests:
    name: Run e2e tests
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run all services from docker-compose
        run: |
          docker-compose -f clusters/docker-compose/docker-compose.yml up -d

      - name: Show which versions are running from each image
        run: docker ps

      - name: Verify that all services are up and running
        uses: HSLdevcom/jore4-tools/github-actions/healthcheck@healthcheck-v1
        with:
          command: '[ -z "$(docker ps -q --filter health=unhealthy)" ]'

      - name: Run e2e smoke tests
        uses: HSLdevcom/jore4-robot/github-actions/run-rf-tests@actions-v1
        with:
          included_tag: smoke
          e2e_username: ${{ secrets.ROBOT_HSLID_EMAIL }}
          e2e_password: ${{ secrets.ROBOT_HSLID_PASSWORD }}

      - name: Upload test results to artifacts
        if: ${{ always() }}
        uses: HSLdevcom/jore4-robot/github-actions/upload-results@actions-v1
