name: Super-Linter

on:
  push:
    branches:
      # pull request branches created by auto updater
      - "autoupdate/**"
  pull_request:
    branches: [main]

jobs:
  # general linter for many languages and tools
  # https://github.com/github/super-linter
  super-linter:
    name: Lint code base
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Super-Linter
        uses: github/super-linter@v4
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_KUBERNETES_KUBEVAL: false # it cannot validate non-default resource types and kustomize patches
          VALIDATE_JSCPD: false # it does not significantly improve the code-base and it's a very slow linter
          VALIDATE_GITHUB_ACTIONS: false # does not handle matrix inputs properly. Does not have a usable ignore syntax for super-linter
